modifying the darwin-ach startup script

diff --git a/scripts/darwin-ach b/scripts/darwin-ach
--- a/scripts/darwin-ach
+++ b/scripts/darwin-ach
@@ -5,7 +5,6 @@ SCREEN_CLIENT=darwin-ach-client
 
 Power()
 {
-
   case "$1" in
 	'on' )
 		On
@@ -20,46 +19,64 @@ Power()
 	;;
   esac
 }
+
 Start()
 {
 
-  CMD_SERVER='darwin-lofaro ach-reset; darwin-lofaro darwin-ach-server on &; sleep 1; On; '
-  CMD_CLIENT='darwin-lofaro ach-reset; darwin-lofaro ach-remote; '
+  rm /tmp/darwin-ach-server.sh
+  rm /tmp/darwin-ach-client.sh
+
+  echo 'darwin-lofaro ach-reset'            >> /tmp/darwin-ach-server.sh
+  echo 'darwin-lofaro darwin-ach-server on' >> /tmp/darwin-ach-server.sh
+  echo 'darwin-lofaro ach-reset'            >> /tmp/darwin-ach-client.sh
+  echo 'darwin-lofaro ach-remote'           >> /tmp/darwin-ach-client.sh
+
+  chmod +x /tmp/darwin-ach-server.sh
+  chmod +x /tmp/darwin-ach-client.sh
+
   case "$2" in
 	'walking' )
-		CMD_SERVER+=' darwin-lofaro darwin-ach-walking'
-		CMD_CLIENT+=' darwin-lofaro darwin-ach-walking'
+		echo 'darwin-lofaro darwin-ach-walking' >> /tmp/darwin-ach-server.sh
+		echo 'darwin-lofaro darwin-ach-walking' >> /tmp/darwin-ach-client.sh
 	;;
   esac
 
   case "$1" in
 	'server' )
-		if ! screen -list | grep -q "$SCREEN_SERVER"; then
-                	echo '--- Starting Darwin-Ach Server using Darwin Lofaro Legacy ---'
-                	screen -d -m -S $SCREEN_SERVER /bin/bash -c $CMD_SERVER
-        	else
-                	echo '--- Darwin-Ach Server usign Darwin Lofaro Legacy already running ---'
-        	fi
+	        echo '--- Starting Darwin-ach Server using Darwin Lofaro Legacy ---'
+		/tmp/darwin-ach-server.sh
+#		if ! screen -list | grep -q "$SCREEN_SERVER"; then
+#                	echo '--- Starting Darwin-Ach Server using Darwin Lofaro Legacy ---'
+#                	screen -d -m -S $SCREEN_SERVER /bin/bash -c /tmp/darwin-ach-server.sh
+#			sleep 2
+#			On
+#        	else
+#                	echo '--- Darwin-Ach Server usign Darwin Lofaro Legacy already running ---'
+#        	fi
 	;;
 
   	'client' )
-		if ! screen -list | grep -q "$SCREEN_CLIENT"; then
-                	echo '--- Starting Darwin-Ach Client using Darwin Lofaro Legacy ---'
-                	screen -d -m -S $SCREEN_CLIENT /bin/bash -c $CMD_CLIENT
-        	else
-                	echo '--- Darwin-Ach Client usign Darwin Lofaro Legacy already running ---'
-        	fi
-		darwin-lofaro ach-reset
-		darwin-lofaro ach-remote
+	        echo '--- Starting Darwin-ach Client using Darwin Lofaro Legacy ---'
+		/tmp/darwin-ach-client.sh
+#		if ! screen -list | grep -q "$SCREEN_CLIENT"; then
+#                	echo '--- Starting Darwin-Ach Client using Darwin Lofaro Legacy ---'
+#                	screen -d -m -S $SCREEN_CLIENT /bin/bash -c /tmp/darwin-ach-client.sh
+#        	else
+#                	echo '--- Darwin-Ach Client usign Darwin Lofaro Legacy already running ---'
+#        	fi
+#		darwin-lofaro ach-reset
+#		darwin-lofaro ach-remote
 	;;
 
 	'local' )
-		if ! screen -list | grep -q "$SCREEN_SERVER"; then
-                	echo '--- Starting Darwin-Ach Server using Darwin Lofaro Legacy ---'
-                	screen -d -m -S $SCREEN_SERVER /bin/bash -c $CMD_SERVER
-        	else
-                	echo '--- Darwin-Ach Server usign Darwin Lofaro Legacy already running ---'
-        	fi
+	        echo '--- Starting Darwin-ach Server (local) using Darwin Lofaro Legacy ---'
+		/tmp/darwin-ach-server.sh
+#		if ! screen -list | grep -q "$SCREEN_SERVER"; then
+#                	echo '--- Starting Darwin-Ach Server using Darwin Lofaro Legacy ---'
+#                	screen -d -m -S $SCREEN_SERVER /bin/bash -c $CMD_SERVER
+#        	else
+#                	echo '--- Darwin-Ach Server usign Darwin Lofaro Legacy already running ---'
+#        	fi
 	;;
 	* )
 		ShowUsage
@@ -70,48 +87,46 @@ Start()
 Stop()
 {
 
-
-
   case "$1" in
 	'server' )
+	        echo '--- Stopping Darwin-ach Server using Darwin Lofaro Legacy ---'
 		darwin-lofaro darwin-ach-walking off
 		Off
 		darwin-lofaro darwin-ach-server off
 		darwin-lofaro ach-clear
-	        echo '--- Stopping Darwin-ach Server using Darwin Lofaro Legacy ---'
-        	screen -S "$SCREEN_SERVER" -X quit > /dev/null
-      		if ! screen -list | grep -q "$SCREEN_SERVER"; then
-                	echo '--- Darwin-ach Server using Darwin Lofaro Legacy Stopped ---'
-        	else
-                	echo '--- Darwin-ach Server using Darwin Lofaro Legacy Failed to Stop ---'
-        	fi
+#        	screen -S "$SCREEN_SERVER" -X quit > /dev/null
+#      		if ! screen -list | grep -q "$SCREEN_SERVER"; then
+#                	echo '--- Darwin-ach Server using Darwin Lofaro Legacy Stopped ---'
+#        	else
+#                	echo '--- Darwin-ach Server using Darwin Lofaro Legacy Failed to Stop ---'
+#        	fi
 	;;
 
   	'client' )
+	        echo '--- Stopping Darwin-ach Client using Darwin Lofaro Legacy ---'
 		darwin-lofaro darwin-ach-walking off
 		darwin-lofaro ach-kill
 		darwin-lofaro ach-clear
-	        echo '--- Stopping Darwin-ach Client using Darwin Lofaro Legacy ---'
-        	screen -S "$SCREEN_CLIENT" -X quit > /dev/null
-      		if ! screen -list | grep -q "$SCREEN_CLIENT"; then
-                	echo '--- Darwin-ach Client using Darwin Lofaro Legacy Stopped ---'
-        	else
-                	echo '--- Darwin-ach Client using Darwin Lofaro Legacy Failed to Stop ---'
-        	fi
+#        	screen -S "$SCREEN_CLIENT" -X quit > /dev/null
+#      		if ! screen -list | grep -q "$SCREEN_CLIENT"; then
+#                	echo '--- Darwin-ach Client using Darwin Lofaro Legacy Stopped ---'
+#        	else
+#                	echo '--- Darwin-ach Client using Darwin Lofaro Legacy Failed to Stop ---'
+#        	fi
 	;;
 
 	'local' )
+		echo '--- Stopping Darwin-ach Server/Client (local) using Darwin Lofaro Legacy ---'
 		darwin-lofaro darwin-ach-walking off
 		Off
 		darwin-lofaro darwin-ach-server off
 		darwin-lofaro ach-clear
-		echo '--- Stopping Darwin-ach Server/Client (local) using Darwin Lofaro Legacy ---'
-        	screen -S "$SCREEN_SERVER" -X quit > /dev/null
-      		if ! screen -list | grep -q "$SCREEN_SERVER"; then
-			echo '--- Darwin-ach Server/Client (local) using Darwin Lofaro Legacy Stopped ---'
-        	else
-			echo '--- Darwin-ach Server/Client (local) using Darwin Lofaro Legacy Failed to Stop ---'
-        	fi
+#        	screen -S "$SCREEN_SERVER" -X quit > /dev/null
+#      		if ! screen -list | grep -q "$SCREEN_SERVER"; then
+#			echo '--- Darwin-ach Server/Client (local) using Darwin Lofaro Legacy Stopped ---'
+#        	else
+#			echo '--- Darwin-ach Server/Client (local) using Darwin Lofaro Legacy Failed to Stop ---'
+#        	fi
 	;;
 	* )
 		ShowUsage
